---
name: Marika
surname: Olijar
position: "Phd Student"
address: "110 North Hall, University of Wisconsin-Madison Madison, WI 53706"
phone: +1 216 712 1781
email: "olijar@wisc.edu"
twitter: MarikaOlijar
github: olijarm
linkedin: marika-olijar-045461170
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Bio

 * Political Science PhD student interested in religion and politics and Central Asian area studies.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Political Science, PhD", "Expected 2026", "University of Pittsburgh", "Madison, WI",
  "Political Science & Slavic Studies, BA, Certificate in Russian, East European and Eurasian Studies", "2020", "University of Pittsburgh", "Pittsburgh, PA") %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Language and Years Studied
```{r}
tribble(
   ~Type, ~Desc,
  "English", "Native proficiency",
  "Russian", "Advanced", 
  "Ukrainian", "Near native proficiency", 
  "Kazakh", "Intermediate"
) %>% 
  brief_entries(
    glue::glue("in {Type}"),
    Desc
  )
```

# Conference presentations
```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ Desc,
  "Organizer - Undergraduate Conference in the Modern Languages: Migrations of Cultures", "Spring 2019", "University of Pittsburgh", "Pittsburgh, PA", "Building Soviet Nations - Reassigning and Redefining Culture in Central Asia") %>% 
  detailed_entries(Degree, Year, Institution, Where, Desc)
```
# Awards and fellowships
```{r}
tribble(
  ~Year, ~Type, ~Desc,
  "2021-22, 2022-23, 2024-25", "University Fellowship", "University Wisconsin-Madison", "2021-2022", "FLAS Fellowship - Intermediate Kazakh Language", "University Wisconsin-Madison"
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year,
    Desc
  )
```
# Professional work experience
```{r}
tribble(
  ~Year, ~Type, ~Desc,
  "2020-Present", "Instructional Materials Developer", "Indiana University Bloomington"
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year,
    Desc
  )
```
